###
GET http://localhost:8080/accounts

###
GET http://localhost:8080/account/047340ea-f385-4b0f-b32a-989a73bd3ac1

###
POST http://localhost:8080/account/create
Content-Type: application/json

{}

###
PUT http://localhost:8080/account/replenish
Content-Type: application/json

{"id": "5e129fcc-b3ec-4bf7-bbfe-1d3846a68eee", "amount": 350}

###
PUT http://localhost:8080/account/withdraw
Content-Type: application/json

{"id": "b23c5788-ed35-4ee3-916a-d1d1016490d6", "amount": 300}

###
PUT http://localhost:8080/account/transfer
Content-Type: application/json

{"idFrom": "b23c5788-ed35-4ee3-916a-d1d1016490d6", "idTo": "5e129fcc-b3ec-4bf7-bbfe-1d3846a68eee", "amount": 150}

###
DELETE http://localhost:8080/account/5e129fcc-b3ec-4bf7-bbfe-1d3846a68eee

### Test git